[features]
resolution = true

[programs.devnet]
manuscript_ideas = "11111111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"

[workspace]
members = ["programs/*"]
